SELECT * FROM customer_behavior.customer;

# some questions about customer shopping behavior... 

# Total revenue generated by male vs female customer ?
select gender , sum(purchase_amount) as revenue from customer_behavior.customer group by gender ;
# MALE = 157890
# FEMALE = 75191

# which customers used a discount but still spent more than the average purchase amount ?

select customer_id, purchase_amount from customer_behavior.customer where  discount_applied = 'Yes' and purchase_amount >= 
( select avg(purchase_amount) from customer_behavior.customer);

# Which are the top 5 products ith the highest average review rating ?

select item_purchased, round(avg(review_rating),2) as "Average Product Rating" from customer_behavior.customer group by item_purchased
 order by avg(review_rating)
 desc limit 5 ;
 
 # Compaare the average Purchase amount between standard and express shipping ?
 
 select shipping_type, round(avg(purchase_amount),2)  from  customer_behavior.customer where shipping_type in ('Standard','Express')
 group by shipping_type ; 
 
 # Express = 60.48
 # Standard = 58.46
 
 # Do subscribed customers spent more ? Comapre average spend and total revenue between subscribed and non-subscribed customers ?
 
 select subscription_status , count(customer_id) as total_customers, round(avg(purchase_amount),2) as avg_spend,
 round(sum(purchase_amount),2) as total_revenue from customer_behavior.customer group by subscription_status order by total_revenue , avg_spend desc;

 # Which 5 products have the highest percentage of purchase with discounts applied??
 
 select item_purchased, round(100 * sum(CASE WHEN discount_applied = "Yes" THEN 1 ELSE 0 END)/ count(*) ,2) as discount_rate 
 from customer_behavior.customer group by item_purchased order by discount_rate desc limit 5;
 
 # Segment customers into new , returning , and loyal based on their previous purchase , and shoe the count of each segment .?
 
 WITH customer_type as (
 select customer_id,previous_purchases,
 CASE 
	WHEN previous_purchases = 1 THEN "New"
	WHEN previous_purchases between 2 and 10 THEN "Returning"
    ELSE "Loyal"
    END as customer_segment
from customer_behavior.customer
 )
 
 select customer_segment, count(*) as "Number of Customers" from customer_type group by customer_segment;

# What are the top 3 most purchase products within each category ??

with item_count as (
select category,item_purchased,count(customer_id) as total_orders,
row_number()  over(partition by category order by count(customer_id)desc) as item_rank 
from customer_behavior.customer
group by category,item_purchased
)

select  item_rank,category,item_purchased,total_orders from item_count
 where item_rank <=3;
 
 # Are customers who are repeat buyers ( more then 5 previous purchase ) also likely to subscribe ??
 
 select subscription_status, count(customer_id) as repeat_buyers 
 from customer_behavior.customer where previous_purchases > 5
 group by subscription_status;
 
 # What is the revenue contribution of each age group ?
 
 select age_group,
 sum(purchase_amount) as total_revenue from customer_behavior.customer group by age_group 
 order by total_revenue desc;

# This is all the insights from the Data of customers from shopping 
